# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build Podlib Framework"
  lane :podlib do
  
    git_pull
    last_git_commit
    sh "rm -f ./Podfile.lock"

    xcbuild(
      scheme: "PodLibAgg",
      workspace: "PodLib.xcworkspace"
    )

  end

  after_all do
    git_add(path:'.')
    git_commit(path: '.',message: "PodLib Framework")
    git_pull
    push_to_git_remote
  end
end